
name: Run Security Scanner Tests For Bash Scaner

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Grant execute permission to security script
        run: chmod +x security_scanner.sh

      - name: Start OWASP Juice Shop
        run: |
          docker run -d -p 3000:3000 bkimminich/juice-shop
          sleep 15  # Wait for the app to start
          
      - name: Run Security Scanner
        run: bash security_scanner.sh
